name: iProxy bot deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install openssh-client

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/${{ secrets.SSH_FILENAME }}
          chmod 400 ~/.ssh/${{ secrets.SSH_FILENAME }}

      - name: Add SSH fingerprint to known_hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: SSH Deploy
        run: |
          ssh -i ~/.ssh/${{ secrets.SSH_FILENAME }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} <<EOF
           sudo systemctl stop ${{ secrets.SERVICE_NAME }}
           cd ${{ secrets.PATH }}
           ssh-agent bash -c 'ssh-add -P "${{ secrets.PASSPHRASE }}" /home/ubuntu/.ssh/id_rsa && git pull'
           source ${{ secrets.VENV_PATH }}/bin/activate
           pip3 install -r requirements.txt
           sudo systemctl start ${{ secrets.SERVICE_NAME }}
          EOF

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} successfully completed!