name: Auto Deploy

on:
  push:
    branches:
      - temp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install openssh-client

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            source botenv/bin/activate
            pid=$(pgrep -f "python main.py")
            for pid in $pids; do
              kill "$pid"
            done
            git pull
            pip3 install -r requirements.txt --no-cache-dir
            nohup python main.py &
